-- Create categories table
create table categories (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add initial categories
insert into categories (key, name) values
  ('animation', '動畫'),
  ('product', '產品展示'),
  ('3d', '3D 動畫'),
  ('explainer', '解說影片'),
  ('youtube', 'YouTube 作品');

-- Add video_order column to videos table
alter table videos add column if not exists video_order integer default 0;

-- Add RLS policies for categories table
alter table categories enable row level security;

-- Allow public read access to categories
create policy "Allow public read access to categories"
  on categories
  for select
  to authenticated, anon
  using (true);

-- Allow admin to manage categories
create policy "Allow admin to manage categories"
  on categories
  for all
  to authenticated
  using (auth.role() = 'admin')
  with check (auth.role() = 'admin');

-- Update existing videos to have sequential order within their categories
with numbered_videos as (
  select 
    id,
    row_number() over (partition by category order by created_at) - 1 as new_order
  from videos
)
update videos
set video_order = numbered_videos.new_order
from numbered_videos
where videos.id = numbered_videos.id;
